# Generated by Django 3.2.6 on 2021-08-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cartitem_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
